coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 65%
        threshold: 2%
comment:
  layout: "diff, flags, files"
  behavior: default
